::: {.content-hidden}
$
{{< include macros.tex >}}
$
:::


# Topology



::: Definition
### Topological space   {#definition-topology}

Let $X$ be a set and $\TT$ a collection of subsets of $X$. We say that $\TT$ is a **topology** on $X$ if the following 3 properties hold:

- (A1) The sets $\emptyset, X$ belong to $\TT$,

- (A2) If $\{A_i\}_{i \in I}$ is an arbitrary family of elements of $\TT$, then
$$
\bigcup_{i \in I} A_i  \in \TT \,.
$$

- (A3) If $A,B \in \TT$ then $A \cap B \in \TT$.

Further, we say:

- The pair $(X,\TT)$ is a **topological space**.
- The elements of $X$ are called **points**.
- The sets in the topology $\TT$ are called **open sets**.
:::





::: Definition
### Trivial topology

Let $X$ be a set. The **trivial topology** on $X$ is the collection of sets
$$
\TTt := \{  \emptyset , X \} \,.
$$


:::



::: Definition
### Discrete topology

Let $X$ be a set. The **discrete topology** on $X$ is the collection of all subsets of $X$
$$
\TTd := \{ A \divider A \subseteq X \} \,.
$$


:::




::: Definition
### Open set of $\R^n$

Let $A \subseteq \R^n$. We say that the set $A$ is **open** if it holds:
$$
\forall \, \xx \in A \,, \,\, \exists \, r > 0 \st B_r(\xx) \subseteq A \,,
$${#eq-open-set-Rn}
where $B_r(\xx)$ is the ball of radius $r>0$ centered at $\xx$
$$
B_r(\xx) := \{ \yy \in \R^n \divider \norm{ \yy - \xx } < r  \} \,, 
$$
and the **Euclidean norm** of $\xx \in \R^n$ is defined by 
$$
\| \xx \| := \sqrt{ \sum_{i=1}^n  x_i^2 } \,.
$$

:::



::: Definition
### Euclidean topology of $\R^n$  {#definition-euclidean-topology}

The **Euclidean topology** on $\R^n$ is the collection of sets
$$
\TTe := \{ A \divider A \subseteq \R^n \,, \,\, A \, \mbox{ is open}  \} \,.
$$

:::


::: Proof
### $\TTe$ is a topology on $\R^n$

To prove $\TTe$ is a topology on $\R^n$, we need to check the axioms:

- (A1) We have $\emptyset , \R^n \in \TTe$: Indeed $\emptyset$ is open because there is no point $\xx$ for which (@eq-open-set-Rn) needs to be checked. Moreover, $\R^n$ is open because (@eq-open-set-Rn) holds with any radius $r>0$. 

- (A2) Let $A_i \in \TTe$ for all $i \in I$. Define the union
  $A =\bigcup_i A_i$. We need to check that $A$ is open. Let $\xx \in A$. By definition of union, there exists an index $i_0 \in I$ such that
  $\xx \in A_{i_0}$. Since $A_{i_0}$ is open, by (@eq-open-set-Rn) there exists $r>0$ such that 
  $B_r(\xx) \subseteq A_{i_0}$. As $A_{i_0} \subseteq A$, we conclude that $B_r(\xx) \subseteq A$, so that $A \in \TTe$.

 - (A3) Let $A, B \in \TTe$. 
  We need to check that $A \cap B$ is open. Let $\xx \in A \cap B$. Therefore $\xx \in A$ and $\xx \in B$. Since $A$ and $B$ are open, by (@eq-open-set-Rn) there exist $r_1,r_2>0$ such that 
  $B_{r_1}(\xx) \subseteq A$ and $B_{r_2}(\xx) \subseteq B$. Set $r := \min\{ r_1,r_2\}$. Then 
  $$
  B_r(\xx) \subseteq B_{r_1}(\xx) \subseteq A  \,, \quad 
  B_r(\xx) \subseteq B_{r_2}(\xx) \subseteq B  \,, 
  $$
  Hence $B_r(\xx) \subseteq A \cap B$, showing that $A \cap B  \in \TTe$.

This proves that $\TTe$ is a topology on $\R^n$.

:::





::: Proposition   
### $B_r(\xx)$ is an open set of $\TTe$ {#proposition-balls-open}

Let $\R^n$ be equipped with the Euclidean topology $\TTe$. Let $r>0$ and $\xx \in \R^n$. Then $B_r(\xx) \in \TTe$.

:::


::: Proof

To prove $B_r(\xx) \in \TTe$, we need to show that $B_r(\xx)$ satisfies (@eq-open-set-Rn). Therefore, let $\yy \in B_r(\xx)$. In particular
$$
\norm{\xx - \yy}<r \,.
$${#eq-balls-open}
Define $\e := r - \norm{\xx - \yy}$.
Note that $\e>0$ by (@eq-balls-open). We claim that 
$$
B_{\e} (\yy) \subseteq B_r (\xx) \,.
$${#eq-proof-ball-open}
Indeed, let $\zz \in B_{\e}(\yy)$. By triangle inequality we have
$$
\| \zz - \xx \| \leq \norm{ \xx - \yy } + \norm{ \yy - \zz } <  \norm{ \xx - \yy } + \e = r \,, 
$$
where we used that $\norm{\yy - \zz} < \e$ and the definition of $\e$. Hence $\zz \in B_r(\xx)$, proving 
(@eq-proof-ball-open). Thus, $B_r(\xx)$ satisfies (@eq-open-set-Rn), ending the proof.


:::




::: Definition 
### Closed set

Let $(X,\TT)$ be a topological space. A set $C \subseteq X$ is **closed**
if 
$$
C^c   \in \TT \,, 
$$
where $C^c:= X \smallsetminus C$ is the complement of $C$ in $X$.
:::




::: Proposition

Let $(X,\TT)$ be a topological space. Properties (A1)-(A2)-(A3) of $\TT$ are equivalent to (C1)-(C2)-(C3), where

- (C1) $\emptyset, X$ are closed.
- (C2) If $C_i$ is closed for all $i \in I$, then
$\bigcap_{i \in I} \, C_i$ is closed.
- (C3) If $C_1,C_2$ are closed then
$C_1 \cup C_2$ is closed.

:::


::: Definition
### Comparing topologies

Let $X$ be a set and let $\TT_1$, $\TT_2$ be topologies on $X$. 

1. $\TT_1$ is **finer** than $\TT_2$ if $\TT_2 \subseteq \TT_1$. 


2. $\TT_1$ is **strictly finer** than $\TT_2$ if $\TT_2 \subsetneq \TT_1$.

3. $\TT_1$ and $\TT_2$ are the **same** topology if $\TT_1 = \TT_2$.
:::





::: Example
### Comparing $\TTt$ and $\TTd$

Let $X$ be a set. Then $\TT_{\textrm{trivial}} \subseteq \TT_{\textrm{discrete}}$.

:::



::: Example
### Cofinite topology on $\R$

**Question.** The **cofinite topology** on $\R$ is the collection of sets
$$
\TTcof := \{ U \subseteq \R \divider U^c \, \mbox{ is finite, }  \mbox{or } U^c = \R \}\,. 
$$

1. Prove that $(\R,\TTcof)$ is a topological space.
2. Prove that $\TTcof \subseteq \TTe$.
3. Prove that $\TTcof \neq \TTe$.


**Solution. Part 1.** Show that the topology properties are satisfied:

(A1) We have $\emptyset \in \TTcof$, since $\emptyset^c = \R$. We have $\R \in \TTcof$ because ${\R}^c = \emptyset$ is finite.

(A2) Let $U_i \in \TTcof$ for all $i \in I$, and define
$U := \bigcup_{i \in I} \,  U_i$. 
By the De Morgan's laws we have
$$
U^c = \left( \cup_{i \in I} \,  U_i    \right)^c = \cap_{i \in I} \, U_i^c \,.
$$
We have two cases:

1. There exists $i_0 \in I$ such that $U_{i_0}^c$ is finite. Then 
$$
U^c = \cap_{i \in I} U_i^c \subset U_{i_0}^c \,,
$$
and therefore $U^c$ is finite, showing that $U \in \TTcof$.

2. None of the sets $U_i^c$ is finite. Therefore $U_i^c = \R$ for all $i \in I$, from which we deduce 
$$
U^c = \cap_{i \in I} U_i^c = \R \quad \implies \quad U \in \TTcof\,.
$$
   
In both cases, we have $U \in \TTcof$, so that (A2) holds.
		
(A3) Let $U,V \in \TTcof$. Set $A=U \cap V$. Then
$$
A^c = U^c \cup V^c \,.
$$
We have $2$ possibilities:

1. $U^c, V^c$ finite: Then $A^c$ is finite, and $A \in \TTcof$.

2. $U^c = \R$ or $V^c = \R$: Then $A^c = \R$, and $A \in \TTcof$.  
    
In all cases, we have shown that $A \in \TTcof$, so that (A3) holds.


**Part 2.** Let $U \in \TTcof$. We have two cases:

- $U^c$ is finite. Then $U^c = \{x_1, \ldots,x_n\}$ for some points $x_i \in \R$. Up to relabeling the points, we can assume that $x_i < x_j$ when $i < j$. Therefore,
$$
U =  \{x_1, \ldots,x_n\}^c = \bigcup_{i=0}^{n} (x_i,x_{i+1}) \,, \quad x_0 := -\infty,\quad x_{n+1} := \infty \,.
$$
The sets $(x_i,x_{i+1})$ are open in $\TTe$, and therefore $U \in \TTe$.

- $U^c = \R$. Then $U = \emptyset$, which belongs to $\TTe$ by (A1).

In both cases, $U \in \TTe$. Therefore $\TTcof \subseteq \TTe$.

**Part 3.** consider the interval $U=(0,1)$. Then $U \in \TTe$. However $U^c$ is neither $\R$, nor finite. Thus $U \notin \TTcof$.

:::




## Sequences

::: Definition
### Convergent sequence

Let $(X,\TT)$ be a topological space. Consider a sequence $\{x_n\} \subseteq X$ and a point
$x \in X$. We say that $x_n$ converges to $x_0$ in the topology $\TT$, if the following property holds:
$$
\begin{aligned}
& \forall \, U \in \TT  \st x_0 \in U\,, \,\, \exists \, N = N(U) \in \N \st  \\
& x_n \in U \,, \, \forall \, n \geq N \,.
\end{aligned}
$$ {#eq-convergence}

The convergence of $x_n$ to $x_0$ is denoted by $x_n \to x_0$.
:::



::: Proposition
### Convergent sequences in $\TTt$ {#proposition-convergence-trivial}


Let $X$ be equipped with $\TTt$. Let $\{x_n\} \subseteq X$, $x_0 \in X$. Then $x_n \to x_0$.


:::



::: Proof

To show that $x_n \to x_0$ we need to check that (@eq-convergence) holds. Let 
$U \in \TTt$ with $x_0 \in U$. We have two cases:

- $U = \emptyset$: There is nothing to prove, since $x_0$ cannot be in $U$. 

- $U = X$: Take $N=1$. Since $U = X$, we have $x_n \in U$ for all $n \geq 1$.  

Thus (@eq-convergence) holds for all the sets $U \in \TTt$, showing that $x_n \to x_0$.

:::



::: Warning

Proposition \ref{proposition-convergence-trivial} shows the topological limit may **not be unique**!

:::



::: Proposition
### Convergent sequences in $\TTd$

Let $X$ be equipped with $\TTd$. Let $\{x_n\} \subseteq X$, $x_0 \in X$. They are equivalent:


1. $x_n \to x_0$ in the topology $\TTd$.
2. $\{x_n\}$ is eventually constant: $\exists \, N \in \N \, \st \, x_n = x_0 , \, \forall \, n \geq N$

:::



::: Proof

*Part 1.* Assume that $x_n \to x_0$. Let $U = \{x_0\}$.
Then $U \in \TTd$. Since $x_n \to x_0$, by (@eq-convergence) there exists $N \in \N$ such that
$$
x_n \in U  \,, \quad \forall \, n \geq N \,.
$$
As $U = \{x_0\}$, we infer $x_n = x_0$ for all $n \geq N$. Hence $x_n$ is eventually constant. 


*Part 2.* Assume that $x_n$ is eventually equal to $x_0$, that is, there exists $N \in \N$ such that 
$$
x_n = x_0 \,, \quad \forall \, n \geq N \,.
$${#eq-convergence-discrete}
Let $U \in \TT$ be an open set such that $x_0 \in U$. By (@eq-convergence-discrete) we have
that 
$$
x_n \in U \,, \quad \forall \, n \geq N \,.
$$
Since $U$ was arbitrary, we conclude that $x_n \to x_0$.
:::



::: Definition
### Classical convergence in $\R^n$

Let $\{\xx_n\} \subseteq \R^n$ and $\xx_0 \in \R^n$. We say that $\xx_n$ converges $\xx_0$ in the 
classical sense if $\norm{\xx_n - \xx_0} \to 0$, that is,
$$
\forall \, \e>0 , \, \exists \, N \in \N , \, \st \norm{\xx_n - \xx_0} < \e  \,, \, \forall \, n \geq N \,.
$$

:::



::: Proposition
### Convergent sequences in $\TTe$  {#proposition-convergence-Rn}

Let $\R^n$ be equipped with $\TTe$. Let $\{x_n\} \subseteq \R^n$, $x_0 \in \R^n$. They are equivalent:


1. $\xx_n \to \xx_0$ in the topology $\TTe$.
2. $\xx_n \to \xx_0$ in the classical sense.
:::


::: Proof

*Part 1.* Assume $\xx_n \to \xx_0$ with respect to $\TTe$. Fix $\e>0$ and define $U := B_{\e}(\xx_0)$. By Proposition \ref{proposition-balls-open}, we have $U \in \TT$. Moreover $\xx_0 \in U$. As $\xx_n \to \xx_0$ with respect to $\TTe$, there exists $N \in \N$ such that 
$$
\xx_n \in U \,, \quad \forall \, n \geq N \,.
$$
As $U = B_{\e}(\xx_0)$, the above reads
$$
\norm{\xx_n - \xx_0} < \e \,, \quad \forall \, n \geq N \,,
$$
showing that $\xx_n \to \xx_0$ in the classical sense.


*Part 2.* Assume $\xx_n \to \xx_0$ in the classical sense. Let $U \in \TTe$ be an arbitrary set such that $\xx_0 \in U$. By definition of Euclidean topology, this means that 
there exists $r>0$ such that $B_r(\xx_0) \subseteq U$.
As $\xx_n \to \xx_0$ in the classical sense, there exists $N \in \N$ such that 
$$
\norm{\xx_n - \xx_0} < r \,, \quad \forall \, n \geq N \,.
$$
By definition of $B_r(\xx_0)$, and since $B_r(\xx_0) \subseteq U$, the above is equivalent to 
$$
\xx_n \in B_{r}(\xx_0) \subseteq U \,, \quad \forall \, n \geq N \,.
$$
As $U$ is arbitrary, we infer $\xx_n \to \xx_0$ with respect to $\TTe$.
:::




::: Proposition

Let $X$ be a set and $\TT_1,\TT_2$ be topologies on $X$. Suppose that $\TT_2 \subseteq \TT_1$. Let $\{x_n\} \subset X$ and $x_0 \in X$. We have
$$
x_n \to x_0 \,\, \mbox{ in } \,\, \TT_1  \quad \implies
\quad 
x_n \to x_0 \,\, \mbox{ in } \,\, \TT_2 \,.
$$

:::




## Metric spaces


::: Definition 
### Distance and Metric space

Let $X$ be a set. A **distance** on $X$ is a function 
$d \colon X \times X \to \R$ such that, for all $x,y,z \in X$ they hold:

- (M1) Positivity: $d(x,y) \geq 0$ and $d(x,y) = 0 \, \iff \, x=y$

- (M2) Symmetry: $d(x,y) = d(y,x)$

- (M3) Triangle Inequality: $d(x,z) \leq d(x,y) + d(y,z)$

The pair $(X,d)$ is called a **metric space**.

:::




::: Definition
### Euclidean distance on $\R^n$

The **Euclidean distance** over $\R^n$ is defined by
$$
d(\xx,\yy) := \norm{ \xx - \yy } = \left(  \sum_{i=1}^n |x_i - y_i|^2   \right)^{1/2}  \,, \quad \forall \xx,\yy \in \R^n \,.
$$
:::


::: Proposition

Let $d$ be the Euclidean distance on $\R^n$. Then $(\R^n,d)$ is a metric space.

:::



::: Definition
### Topology induced by the metric  {#definition-metric-topology}

Let $(X,d)$ be a metric space. The set $A \subseteq X$ is **open** if it holds
$$
\forall \, x \in U \,, \, \exists \, r \in \R, \, r > 0 \, \st \, B_r(x) \subseteq U \,,
$$
where $B_r(x)$ is the ball centered at $x$ of radius $r$, defined by 
$$
B_r(x) = \{ y \in X  \, \colon \,  d(x,y)<r  \} \,.
$$
The topology **induced by the metric** $d$ is the
collection of sets
$$
\TT_d = \{ U\, \colon \, U \subseteq X, \, U \text{ open}   \}\,.
$$

:::




::: Remark
### Topology induced by Euclidean distance

Consider the metric space $(\R^n,d)$ with $d$ the Euclidean distance. Then 
$$
\TT_d = \TTe \,,
$$
where $\TTe$ is the Euclidean topology on $\R^n$. 


:::




::: Example
### Discrete distance

**Question.** Let $X$ be a set. The **discrete distance** is the function $d \colon X \times X \to \R$ defined by
$$
d(x,y) := 
\begin{cases}
	0 & \mbox{ if } \, x = y \\
	1 & \mbox{ if } \, x \neq y 
\end{cases}
$$

1. Prove that $(X,d)$ is a metric space.
2. Prove that $\TT_d = \TT_{\textrm{discrete}}$.


**Solution.** See Question 3 in Homework 3.
:::




::: {.Proposition #proposition-metric-ball}


Let $(X,d)$ be a metric space, $\TT_d$ the topology induced by $d$. Then:

- For all $x \in X$, $r>0$ we have $B_r(x) \in \TT_d$.
- $U \in \TT_d$ if and only if $\exists \, I$ family of indices s.t.
$$
U = \bigcup_{ i \in I } B_{r_i}(x_i) \,, \quad 
x_i \in X , \,\, r_i > 0 \,.
$$

:::




::: Proposition
### Convergence in metric space

Suppose $(X,d)$ is a metric space and $\TT_d$ the topology induced by $d$. Let $\{x_n\} \subseteq X$ and $x_0 \in X$. They are equivalent:

1. $x_n \to x_0$ with respect to the topology $\TT_d$.
2. $d(x_n,x_0) \to 0$ in $\R$.
3. For all $\e>0$ there exists $N \in \N$ such that 
$$
x_n \in B_r(x_0) \, , \,\, \forall \, n \geq \N \,.
$$

:::



## Interior, closure and boundary

::: Definition
### Interior of a set

Let $(X,\TT)$ be a topological space, $A \subseteq X$. The **interior** of $A$ is
$$
\interior{A} :=  \bigcup_{ \substack{U \subseteq A \\ U \in \TT} } \, U \,.
$$

:::



::: Proposition
### $\interior{A}$ is the largest open set contained in $A$

Let $(X,\TT)$ be a topological space, $A \subseteq X$. Then
$\interior{A}$ is the largest open set contained in $A$, that is:

1. $\interior{A}$ is open.
2. $\interior{A} \subseteq A$.
3. If $V \in \TT$ and $V \subseteq A$, then $V \subseteq \interior{A}$.
4. $A$ is open if and only if $A = \interior{A}$.

:::




::: Definition
### Closure of a set

Let $(X,\TT)$ be a topological space, $A \subseteq X$. The **closure** of $A$ is
$$
\closure{A} :=  \bigcap_{ \substack{A \subseteq C \\ C \, \text{closed} } } \, C \,.
$$

:::




::: Proposition
### $\closure{A}$ is the smallest closed set containing $A$

Let $(X,\TT)$ be a topological space, $A \subseteq X$. Then
$\closure{A}$ is the smallest closed set containing $A$, that is:

1. $\closure{A}$ is closed.
2. $A \subseteq \closure{A}$.
3. If $V$ is closed $A \subseteq V$, then $\closure{A} \subseteq V$.
4. $A$ is closed if and only if $A = \closure{A}$.

:::



::: {.Lemma #lemma-closure-intersection}

Let $(X,\TT)$ be a topological space, $A \subseteq X$. They are equivalent:

1. $x_0 \in \closure{A}$.
2. For every $U \in \TT$ such that $x_0 \in U$, it holds
$$
U \cap A \neq \emptyset  \,.
$$

:::




::: Definition
### Boundary of a set

Let $(X,\TT)$ be a topological space, $A \subseteq X$. The **boundary** of $A$ is
$$
\partial A := \closure{A} \smallsetminus \interior{A} \,.
$$

:::


::: Proposition

Let $(X,\TT)$ be a topological space, and $A \subseteq X$. Then
$\partial A$ is closed.

:::



::: Definition
### Set of limit points

Let $(X,\TT)$ be a topological space, $A \subseteq X$. The set of
**limit points** of $A$ is defined as
$$
L(A):=\{  x \in X \divider \exists \, \{x_n \} \subseteq A \st x_n \to x    \} \,.
$$

:::


::: {.Proposition #proposition-closure-sequence}


Let $(X,\TT)$ be a topological space, $A \subseteq X$ a set. 
Let $\{x_n\} \subseteq A$ and $x_0 \in X$ be such that $x_n \to x_0$. Then
$x_0 \in \closure{A}$. In particular,
$$
L(A) \subseteq \closure{A} \,.
$$

:::


::: Proof

Suppose by contradiction $x_0 \notin \closure{A}$, so that
$$
x_0 \in (\closure{A})^c \,.
$$
Since $(\closure{A})^c$ is open and $x_n \to x_0$, there exists $N \in \N$
such that 
$$
x_n \in (\closure{A})^c \,, \quad \forall \, n \geq N \,.
$$
This is a contradiction, since we were assuming that $\{x_n\} \subseteq A$. This shows $x_0 \in \closure{A}$ and therefore
$L(A) \subseteq \closure{A}$.


:::



::: Warning

1. The converse of Proposition \ref{proposition-closure-sequence} is false
in general, that is, 
$$
\closure{A} \not\subset L(A) \,.
$$
We show a counterexample in Example \ref{example-closure-counter}.

2. The relation  
$$
\closure{A} = L(A) \,.
$$
holds in the so-called first countable topological spaces,
such as metric spaces, see Proposition \ref{proposition-closure-metric} below.
:::


::: {.Example #example-closure-counter}
### Co-countable topology on $\R$

**Question.** The **co-countable** topology on $\R$ is the collection of sets 
$$
\TTcc := \{ A \subseteq \R \divider A^c = \R \,\, \mbox{ or } \,\, A^c \,
\mbox{ countable }\} \,.
$$

1. Prove that $\TTcc$ is a topology on $\R$.

2. Prove that a sequence $\{x_n\}$ is convergent in $\TTcc$ if and only if it is eventually constant. 

3. Define the set $A = (-\infty,0]$. Prove that $\closure{A} = \R$. 

4. Conclude that $\closure{A} \not\subset L(A)$.



**Solution.** 

1. See Question 2 in Homework 3.

2. See Question 2 in Homework 3.

3. Assume $C$ is a closed set such that $A \subseteq C$. Since $C$ is closed, it follows that $C^c \in \TTcc$. Therefore $(C^c)^c = C$ is either countable, or equal to $\R$. As $A \subseteq C$, we have that $C$ is uncountable. Therefore, $C = \R$. As $C$ is an arbitrary closed set containing $A$, we conclude that
$$
\closure{A} =\bigcap_{ \substack{  A \subseteq C    \\ C \, \text{closed}  }   } \, C = \bigcap_{ \substack{  A \subseteq C    \\ C \, \text{closed}  }   } \, \R  = \R \,. 
$$

4. By Point 2, convergent sequences are eventually constant. Therefore, if $\{x_n\} \subseteq A$ converges to $x_0$, we conclude that $x_0 \in A$. This shows  
$$
L(A) = A = [-\infty , 0) \,.
$$
By Point 3, we have $\closure{A} = \R$. We conclude that
$\closure{A} \not\subset L(A)$.

:::



::: Proposition 
### Characterization of $\interior{A}$ and $\closure{A}$ in metric space {#proposition-closure-metric}

Let $(X,d)$ be a metric space. Denote by $\TT_d$ the topology induced by $d$. For any $A \subseteq X$, we have

1. $\interior{A} = \{ x \in A \divider \exists \,\, r>0  \st B_r(x) \subseteq A \}$ ,

2. $\closure{A} = L(A) = \{  x \in X \st \exists \,\, \{ x_n \} \subseteq A \st x_n \to x   \}$.


:::



::: Proof

1. See Question 4 in Homework 3.

2. The inclusion $L(A) \subseteq \closure{A}$ holds by Proposition \ref{proposition-closure-sequence}. We are left to show that
$$
\closure{A} \subseteq L(A) \,.
$$
To this end, let $x_0 \in \closure{A}$. For $n \in \N$, consider the ball $B_{1/n}(x_0)$. Since
$B_{1/n}(x_0) \in \TT_d$ and $x_0 \in B_{\e}(x_0)$, we can apply Lemma \ref{lemma-closure-intersection} and deduce that
$$
B_{1/n}(x_0) \cap A \neq \emptyset \,.
$$
Let $x_n \in B_{1/n}(x_0) \cap A$. Since $n$ was arbitrary, we have constructed a sequence
$\{x_n\} \subseteq A$ such that 
$$
x_n \in B_{1/n}(x_0) \,, \quad \forall \, n \in \N \,.
$$
In particular, we have that 
$$
0 \leq d(x_n,x_0) < \frac{1}{n} \to 0
$$
as $n \to \infty$. Thus $x_n \to x_0$, showing that $x_0 \in L(A)$.
:::




::: Example

**Question.** Consider $\R$ equipped with the Euclidean topology. Let $A =[0,1)$. Prove that:
$$
\interior{A} = (0,1) \,, \quad \closure{A} = [0,1] \,, \quad \partial A = \{0,1\} \,.
$$

**Note:** In particular, this shows
$$
\interior{A}  \neq A \,, \quad \closure{A} \neq A \,,
$$
so that $A$ is neither open, nor closed. 

**Solution.** See Question 5 in Homework 3.

:::





::: Definition
### Density

Let $(X,\TT)$ be a topological space. We say that a subset $A \subseteq X$ is **dense** in $X$, if 
$$
A \cap U \neq \emptyset \,, \quad \, \forall \,\, U \in \TT\,, \,\, U \neq \emptyset \,.
$$

:::



::: Proposition
### Characterization of density {#proposition-density}

Let $(X,\TT)$ be a topological space, $A \subseteq X$. They are equivalent:

1. $A$ is dense in $X$.
2. It holds $\closure{A} = X$.

:::



::: Example
### $\Z$ is not dense in $(\R,\TTe)$

**Question.** Consider $\R$ equipped with the Euclidean topology $\TTe$. Prove that the set of integers $\Z$ is not dense in $\R$, with 
$$
\closure{\Z} = \Z \,.
$$

**Solution.** The set of integers $\Z$ satisfies
$$
\Z^c = \bigcup_{ z \in \Z}  \, (z , z + 1 ) \,. 
$$
Since $(z,z+1)$ is open in $\R$, by (A2) we conclude that 
$\Z^c$ is open, so that $\Z$ is closed. Therefore 
$$
\closure{\Z} = \Z \,.
$$
As $\closure{\Z} \neq \R$, by Proposition \ref{proposition-density}, we have that $\Z$ is not dense in $\R$.

:::





::: Example
### $\Z$ is dense in $(\R,\TTcof)$

**Question.** Consider $\R$ equipped with the cofinite topology
$$
\TTcof = \{ U \subset \R \divider U^c \, \mbox{ is finite, }  \mbox{ or } U^c = \R \}\,. 
$$
Prove that $\Z$ is dense in $\R$. In particular,
$$
\closure{\Z } = \R \,,
$$

**Solution.** Suppose $C$ is a closed set such that $\Z \subseteq C$. By definition of $\TTcof$, we have that $(C^c)^c = C$ is either finite, or it coincides with $\R$. Since $\Z \subseteq C$, and $\Z$ is not finite, we conclude $C = \R$.
As $C$ is an arbitrary closed set containing $\Z$, we conclude that
$$
\closure{\Z} =\bigcap_{ \substack{  \Z \subseteq C    \\ C \, \text{closed}  }   } \, C = \bigcap_{ \substack{  \Z \subseteq C    \\ C \, \text{closed}  }   } \, \R  = \R \,. 
$$ 
In particular, by Proposition \ref{proposition-density}, $\Z$ is dense in $\R$.

:::





## Hausdorff spaces




::: Definition
### Hausdorff space

We say that a topological space $(X,\TT)$ is **Hausdorff** if for every $x,y \in X$ with $x \neq y$, there exist $U,V \in \TT$ such that
$$
x \in U \,, \quad y \in V \,, \quad U \cap V = \emptyset \,.
$$

:::




::: {.Proposition  #proposition-hausdorff-1}

Let $(X,d)$ be a metric space, $\TT_d$ the topology induced by $d$. Then $(X, \TT_d)$ is a Hausdorff space.

:::


::: Proof

Let $x,y \in X$ with $x \neq y$. Define
$$
U := B_{\e}(x)\,, \quad 
V := B_{\e}(y) \,, \quad \e := \frac12 \, d(x,y) \,.
$$
By Proposition \ref{proposition-metric-ball}, we know that $U, V \in \TT_d$. Moreover $x \in U$, $y \in V$. We are left to show that $U \cap V = \emptyset$.
Suppose by contradiction that $U \cap V \neq \emptyset$ and let $z \in U \cap V$. Therefore 
$$
d(x,z) < \e \,,  \quad d(y,z) < \e \,.
$$
By triangle inequality we have
$$
d(x,y) \leq d(x,z) +  d(y,z) < \e + \e = d(x,y) \,,
$$
where in the last inequality we used the definition of $\e$. This is 
a contradiction. Therefore $U \cap V = \emptyset$ and $(X,\TT_d)$ is Hausdorff.


:::


::: Definition
### Metrizable space

Let $(X,\TT)$ be a topological space. We say that the topology $\TT$ is **metrizable** if there
exists a metric $d$ on $X$ such that
$$
\TT = \TT_d \,,
$$
with $\TT_d$ the topology induced by $d$.

:::


::: {.Corollary #corollary-hausdorff}

Let $(X,\TT)$ be a metrizable space. Then $X$ is Hausforff.

:::





::: Example
### $(X,\TTt)$ is not Hausdorff

**Question.** Let $X$ be equipped with the trivial topology $\TTt$. Then $X$ is not Hausdorff.

**Solution.** Assume by contradiction $(X,\TTt)$ is Hausdorff and let $x,y \in X$ with $x \neq y$. Then, there exist $U,V \in \TTt$ such that 
$$
x \in U \,, \quad y \in V \,, \quad U \cap V = \emptyset \,.
$$
In particular $U \neq \emptyset$ and $V \neq \emptyset$. Since $\TT = \{  \emptyset, X \}$, we conclude that
$$
U = V = X  \quad \implies \quad U \cap V  = X \neq \emptyset \,.
$$
This is a contradiction, and thus $(X,\TTt)$ is not Hausdorff.


:::




::: Example
### $(\R,\TTcof)$ is not Hausdorff

**Question.** Consider the cofinite topology on $\R$
$$
\TTcof = \{ U \subseteq \R \divider U^c \, \mbox{ is finite, }  \mbox{or } U^c = \R \} \,. 
$$
Prove that $(\R,\TTcof)$ is not Hausdorff. 

**Solution.** Assume by contradiction $(\R,\TTcof)$ is Hausdorff and let $x, y \in \R$ with $x \neq y$. Then, there exist $U,V \in \TTcof$ such that 
$$
x \in U \,, \quad y \in V \,, \quad U \cap V = \emptyset \,.
$$
Taking the complement of $U \cap V = \emptyset$, we infer
$$
\R = (U \cap V)^c = U^c \cup V^c \,.
$${#eq-Q31}
There are two possibilities:
	
1. $U^c$ and $V^c$ are finite. Then $U^c \cup V^c$ is finite, so that (@eq-Q31) is a contradiction.

2. Either $U^c = \R$ or $U^c = \R$. If $U^c = \R$, then $U = \emptyset$. This is a contradiction, since $x \in U$. If $V^c = \R$, then $V = \emptyset$. This is a contradiction, since $y \in V$. 

Hence $(\R,\TTcof)$ is not Hausdorff.

:::




::: Example
## Lower-limit topology on $\R$ is not Hausdorff

**Question.** The **lower-limit topology** on $\R$ is the collection of sets
$$
\TTll =\{\emptyset, \R\} \cup \{ (a,+\infty) \, \colon \, a \in \R \} \,.
$$

1. Prove that $(\R,\TTll)$ is a topological space.
2. Prove that $(\R,\TTll)$ is not Hausdorff.

**Solution. Part 1.** We show that $(\R, \TTll)$ is a topological space by verifying the axioms:

(A1) By definition $\emptyset, \R \in \TTll$.

(A2) Let $A_i \in \TTll$ for all $i \in I$. We have 2 cases:

- If $A_i = \emptyset$ for all $i$, then $\cup_i A_i = \emptyset \in \TTll$. 

- At least one of the sets $A_i$ is non-empty. As empty-sets do not contribute to the union, we can discard them. Therefore, $A_i = (-\infty, a_i)$ with $a_i \in \R \cup \{\infty\}$. Define:
$$
a := \sup_{i \in I} a_i, \quad A := (-\infty, a).
$$
Then $A \in \mathcal{T}$ and:
$$
A = \cup_{i \in I} A_i.
$$
To prove this, let $x \in A$. Then $x < a$, so there exists $i_0 \in I$ such that $x < a_{i_0}$. Thus, $x \in A_{i_0}$, showing $A \subseteq \cup_{i \in I} A_i$. Conversely, if $x \in \cup_{i \in I} A_i$, then $x \in A_{i_0}$ for some $i_0 \in I$, implying $x < a_{i_0} \leq a$. Thus, $x \in A$, proving $\cup_{i \in I} A_i \subseteq A$.

(A3) Let $A, B \in \TTll$. We have 3 cases:

- $A = \emptyset$ or $B = \emptyset$. Then $A \cap B = \emptyset \in \TTll$.

- $A \neq \emptyset$ and $B \neq \emptyset$. Therefore, $A = (-\infty, a)$ and $B = (-\infty, b)$ with $a, b \in \R \cup \{\infty\}$. Define
$$
U := A \cap B, \quad z := \min\{a, b\}.
$$
Then $U = (-\infty, z) \in \TTll$.

Thus, $(\R, \TTll)$ is a topological space.

**Part 2.** To show $(\R, \TTll)$ is not Hausdorff, assume otherwise. Let $x, y \in \R$ with $x \neq y$. Then there exist $U, V \in \TTll$ such that:
$$
x \in U, \quad y \in V, \quad U \cap V = \emptyset.
$$
As $U,V$ are non-empty, by definition of $\TTll$, there exist $a, b \in \R \cup \{\infty\}$ such that $U = (-\infty, a)$ and $V = (-\infty, b)$. Define:
$$
z := \min\{a, b\}, \quad Z := U \cap V = (-\infty, z).
$$
Hence $Z \neq \emptyset$, contradicting $U \cap V = \emptyset$. Thus, $(\R, \TTll)$ is not Hausdorff.


:::




::: Proposition
### Uniqueness of limit in Hausdorff spaces

Let $(X,\TT)$ be a Hausdorff space. If a sequence $\{x_n\} \subseteq X$ converges, then the limit is unique.

:::


::: Proof

Let $\{x_n\} \subseteq X$ be convergent, and suppose by contradiction that 
$$
x_n \to x_0 \,, \quad x_n \to y_0 \,, \quad  x_0 \neq y_0 \,.
$$
Since $X$ is Hausdorff, there exist $U,V \in \TT$ such that 
$$
x_0 \in U \,, \quad y_0 \in V \,, \quad U \cap V = \emptyset \,.
$$
As $x_n \to x_0$ and $U \in \TT$ with $x_0 \in U$, there exists
$N_1 \in \N$ such that
$$
x_n \in U \,, \quad \forall \, n \geq N_1  \,.
$$
Similarly, since $x_n \to y_0$ and $V \in \TT$ with $y_0 \in U$, there exists
$N_2 \in \N$ such that
$$
x_n \in V \,, \quad \forall \, n \geq N_2  \,.
$$
Take $N:=\max\{N_1,N_2\}$. Then 
$$
x_n \in U \cap V \,, \quad \forall \, n \geq N  \,.
$$
Since $U \cap V = \emptyset$, the above is a contradiction. Therefore the limit is unique. 

:::





## Continuity


::: Definition
### Images and Pre-images

Let $X, Y$ be sets and $f \colon X \to Y$ be a function. 

1. Let $U \subseteq X$. The image of $U$ under $f$ is the subset of $Y$ defined by
$$
f (U) := \{ y \in Y \divider \exists \, x \in X \st y = f(x) \} = \{ f(x) \divider x \in X \} \,.
$$

2. Let $V \subseteq Y$. The pre-image of $V$ under $f$ is the subset of $X$ defined by
$$
f^{-1} (V) := \{ x \in X \divider f(x) \in V \} \,.
$$

:::


::: Warning

The notation $f^{-1}(V)$ does not mean that we are inverting $f$. In fact, the pre-image is defined for all functions.

:::



::: Definition
### Continuous function

Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be topological spaces. Let $f \colon X \to Y$ be a function. 

1. Let $x_0 \in X$. We say that $f$ is continuous at $x_0$ if it holds:
$$
\forall \, V \in \TT_Y \st f(x_0) \in V \,, \,\, \exists \, U \in \TT_X \st x_0 \in U \,, \,\, f(U) \subseteq V \,.
$$

2. We say that $f$ is continuous from $(X,\TT_X)$ to $(Y,\TT_Y)$ if $f$ is continuous at each point $x_0 \in X$.

:::



::: {.Proposition  #proposition-continuity-characterization}

Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be topological spaces. Let $f \colon X \to Y$ be a function. They are equivalent:

1. $f$ is continuous from $(X,\TT_X)$ to $(Y,\TT_Y)$.
2. It holds: $f^{-1}(V) \in \TT_X$ for all $V \in \TT_Y$.

:::


::: Example

**Question.** Let $X$ be a set and $\TT_1$, $\TT_2$ be topologies on $X$. Define the identity map
$$
{\id}_{X} \colon (X,\TT_1) \to (X,\TT_2)  \,, \quad {\id}_{X} (x):= x \,.
$$
Prove that they are equivalent:

1. ${\id}_{X}$ is continuous from $(X,\TT_1)$ to $(X,\TT_2)$.
2. $\TT_1$ is finer than $\TT_2$, that is, $\TT_2 \subseteq \TT_1$.

**Solution.** ${\id}_{X}$ is continuous if and only if
$$
{\id}_{X}^{-1} (V) \in \TT_1  \,, \quad \forall \, V \in \TT_2 \,.
$$
But ${\id}_{X}^{-1} (V) = V$, so that the above reads
$$
V \in \TT_1  \,, \quad \forall \, V \in \TT_2 \,,
$$
which is equivalent to $\TT_2 \subseteq \TT_1$.

:::



::: Definition
### Continuity in the classical sense

Let $f \colon \subseteq \R^n \to \R^m$. We say that $f$ is continuous at $\xx_0$ if it holds:
$$
\forall \, \e > 0 \,, \, \exists \, \delta >0 \st \|f(\xx) - f(\xx_0)\|< \e \,\, \mbox{ if } \,\, \| \xx - \xx_0 \| < \delta \,.   
$$

:::


::: Proposition

Let $f \colon  \R^n \to \R^m$ and suppose $\R^n,\R^m$ are 
equipped with the Euclidean topology. Let $\xx_0 \in \R^n$. They are equivalent:

1. $f$ is continuous at $\xx_0$ in the topological sense.
2. $f$ is continuous at $\xx_0$ in the classical sense.

:::

 


::: Proposition

Let $(X,d_X)$ and $(Y,d_Y)$ be metric spaces. Denote by $\TT_X$ and $\TT_Y$ the topologies induced by the metrics. Let $f \colon X \to Y$ and $x_0 \in X$. They are equivalent:

1. $f$ is continuous at $x_0$ in the topological sense.
2. It holds:
$$
\begin{aligned}
& \forall \, \e > 0 \,, \, \exists \, \delta >0 \st \\
& d_Y(f(x),f(x_0))<\e \,\, 
\mbox{ if } \,\, d_X(x , x_0) < \delta \,.
\end{aligned}
$$

:::


::: Example

**Question.** Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be a topological space. Suppose that 
$\TT_Y$ is the trivial topology, that is,
$$
\TT_Y = \{ \emptyset, Y \} \,.
$$
Prove that every function $f \colon X \to Y$ is continuous. 

**Solution.** $f$ is continuous if $f^{-1}(V) \in \TT_X$ for all $V \in \TT_Y$. We have two cases:

- $V=\emptyset$: Then 
$f^{-1}(V) = f^{-1}(\emptyset) = \emptyset \in \TT_X$.

- $V=Y$: Then $f^{-1}(V) = f^{-1}(Y) = X \in \TT_X$.

Therefore $f$ is continuous.

:::



::: Example

**Question.** Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be topological spaces. Suppose that 
$\TT_Y$ is the discrete topology, that is,
$$
\TT_Y = \{ V \st V \subseteq Y \} \,.
$$
Let $f \colon X \to Y$. Prove that they are equivalent:

1. $f$ is continuous from $X$ to $Y$.
2. $f^{-1}(\{y\}) \in \TT_X$ for all $y \in Y$.  


**Solution.** Suppose that $f$ is continuous. Then
$$
f^{-1}(V) \in \TT_X \,, \quad \forall \,\, V \in \TT_Y \,.
$$
As $V=\{y\} \in \TT_Y$, we conclude that $f^{-1}(\{y\}) \in \TT_X$.

Conversely, assume that $f^{-1}(\{y\}) \in \TT_X$ for all $y \in Y$.  Let $V \in \TT_Y$. Trivially, we have $V = \cup_{y \in V} \, \{ y \}$.
Therefore 
$$
f^{-1}(V) = f^{-1}\left( \bigcup_{y \in V}\, \{ y \} \right) = \bigcup_{y \in V} \, f^{-1}( \{y \} ) \,.
$$
As $f^{-1}( \{y \}) \in \TT_X$ for all $y \in Y$, by property (A2) we conclude that $f^{-1}(V) \in \TT_X$. Therefore $f$ is continuous.

:::



::: Definition 
### Sequential continuity

Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be topological spaces, and  $f \colon X \to Y$. We say that $f$ is **sequentially continuous** if the following condition holds:
$$
\{x_n\} \subset X \,, \,\, x_n \to x_0 \,\, \mbox{ in }\, X \,\, \implies \,\,   
f(x_n) \to f(x_0) \,\, \mbox{ in }\, Y\,.
$$

:::


::: {.Proposition #proposition-continuity-sequential}

Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be topological spaces. Let 
$f \colon X \to Y$ be continuous. Then $f$ is sequentially continuous.

:::



::: Warning

1. The reverse implication of Proposition \ref{proposition-continuity-sequential} is false:
$$
\text{sequential continuity} \quad  \centernot\implies \quad \text{continuity}
$$ 
A counterexample is given in Example \ref{example-sequential-continuity} below.

2. Continuity is equivalent to sequential continuity if the topologies on
$X$ and $Y$ are first countable. This is the case for metrizable topologies, see
Proposition \ref{proposition-sequential-continuity} below.

:::



::: {.Proposition  #proposition-sequential-continuity}

Let $(X,d_X)$ and $(Y,d_Y)$ be metric spaces. They are equivalent:

1. $f$ is continuous.
2. $f$ is sequentially continuous.

:::




::: {.Example  #example-sequential-continuity}
### Sequential continuity does not imply continuity

**Question.** Consider the co-countable and discrete topologies on $\R$
\begin{gather*}
\TTcc = \{ A \subseteq \R \divider A^c = \R  \, \mbox{ or } \, A^c \, \mbox{ countable} \} \\
\TTd = \{ A \subseteq \R \}
\end{gather*}
Consider the identity function
$$
f \colon (\R,\TTcc) \to (\R,\TTd) \,, \quad f(x):=x \,.
$$
Prove that 

1. $f$ is not continuous.
2. $f$ is sequentially continuous.

*Hint: You can use the following fact: Sequences in $(\R,\TTcc)$ and $(\R,{\TTd})$ converge if and only if they are eventually constant.*

**Solution.**

1.  We have $\{x\} \in {\TT}_{\textrm{discrete}}$. However,
    $$
    f^{-1}(\{ x\}) = \{x\} \notin {\TT}_{\textrm{cc}} \,,
    $$
    since $\{x\}^c = \R \smallsetminus \{x\}$ is neither equal to $\R$, nor countable. Therefore $f$ is not continuous.

2. Assume that $\{x_n\}$ is convergent in $\TTcc$. By the Hint, we have that $\{x_n\}$ is eventually constant. Again by the Hint, we infer that $\{x_n\}$ is convergent in $\TTd$. Since $f(x_n) = x_n$, we conclude that $f$ is sequentially continuous.

:::



:::  Proposition
### Continuity of compositions

Let $(X,\TT_X), (Y,\TT_Y), (Z,\TT_Z)$ be topological spaces. Assume $f \colon X \to Y$ and $g \colon Y \to Z$ are continuous. Then $(g \circ f) \colon X \to Z$ is continuous.
:::

::: Definition
### Homeomoprhim

Let $(X,\TT_X)$, $(Y,\TT_Y)$ be topological space. A function $f \colon X \to Y$ is called an **homeomorphism** if they hold:

1. $f$ is continuous.
2. $f$ admits continuous inverse $f^{-1} \colon Y \to X$.

:::



## Subspace topology


::: Definition
### Subspace topology   {#definition-subspace-topology}

Let $(X,\TT)$ be a topological space and $Y \subseteq X$ a subset. Define the family of sets
\begin{align*}
\SSS & := \{ A \subseteq Y \divider \exists \,\, U \in \TT \st A = U \cap Y   \} \\
     & = \{ U \cap Y , \,\, U \in \TT  \} \,.
\end{align*}
The family $\SSS$ is the **subspace topology** on $Y$ induced by the inclusion $Y \subseteq X$.

:::



::: Proposition

Let $(X,\TT)$ be a topological space and $Y \in \TT$. Let  
$A \subseteq Y$. Then
$$
A \in \SSS \quad \iff \quad A \in \TT \,.
$$

:::



::: Warning

Let $(X,\TT)$ be a topological space, $A \subseteq Y \subseteq X$. In general we could have
$$
A \in \SSS \quad \mbox{and} \quad A \notin \TT \,.
$$

**Example.** Let $X=\R$ with $\TTe$. Consider the subset $Y = [0,2)$, and equip $Y$ with the subspace topology $\SSS$. Let $A = [0,1)$. Then $A \notin \TTe$ but $A \in \SSS$, since 
$$
A =  (-1,1)  \cap Y \,, \qquad (-1,1) \in \TTe \,.
$$


:::




::: Example

**Question.** Let $X=\R$ be equipped with $\TTe$. Let 
$\SSS$ be the subspace topology on $\Z$. Prove that
$$
\SSS = \TTd \,.
$$


**Solution.** To prove that $\SSS = \TTd$, we need to show that all the subsets of $\Z$ are open in $\SSS$.

1. Let $z \in \Z$ be arbitrary. Notice that 
$$
\{z\} = \left(  z-1 , z + 1   \right)   \cap \Z \,
$$
and $(z - 1, z + 1) \in \TTe$. Thus $\{z\} \in \SSS$. 

2. Let now $A \subseteq \Z$ be an arbitrary subset. Trivially,
$$
A = \cup_{z \in A} \, \{ z \} \,.
$$
As $\{z\} \in \SSS$, we infer that $A \in \SSS$ by (A2).

:::




## Topological basis

::: Definition
### Topological basis

Let $(X,\TT)$ be a topological space and let $\mathcal{B} \subseteq \TT$.  We say that 
$\mathcal{B}$ is a **topological basis** for the topology $\TT$, if for all $U \in \TT$ 
there exist open sets $\{B_i\}_{i \in I} \subseteq \mathcal{B}$, with $I$ family of indices, such that 
$$
U = \bigcup_{i \in I} \, B_i \,.
$${#eq-topo-basis}


:::



::: Example

**Question.** Prove the following statements.

1. Let $(X,\TT)$ be a topological space. Then $\mathcal{B}:=\TT$ is a basis for $\TT$.  
    
   
2. Let $(X,d)$ be a metric space with topology $\TT_d$ induced by the metric. Then
$$
\mathcal{B} :=\{ B_r(x) \divider x \in X \,, \,\, r>0  \}
$$
is a basis for $\TT_d$.

   

3. Let $X$ be equipped with $\TTd$. Then
$$
\mathcal{B}:=\{   \{x\}  \divider x \in X \}
$$
is a basis for $\TTd$.  

   

**Solution.**

1. This is true because one can just take $B=U$ in (@eq-topo-basis).

2. This is true by Propostion \ref{proposition-metric-ball}.

3. This is true because for any $U \in \TT$ we have 
$$
U = \bigcup_{ x \in U }  \, \{x\} \,. 
$$

:::




::: Example

**Question.** Consider $\R$ equipped with the Euclidean topology $\TTe$. Which of the following collection of sets are basis for $\TTe$? Motivate your answer.

1. $\mathcal{B}_1 = \{ (a,b) \,\colon \, a,b \in \R \}$.
2. $\mathcal{B}_2 = \{ (a,b) \,\colon \, a,b \in \Q \}$.
3. $\mathcal{B}_3 = \{ (a,b) \,\colon \, a,b \in \Z \}$.

**Solution.**

1. $\mathcal{B}_1$ is a basis for $\TTe$, for the following reason. Let $d$ be the Euclidean distance on $\R$, and $\TT_d$ the topology induced by $d$. We know that $\TT_d = \TTe$, therefore 
$$
\mathcal{B} :=\{ B_r(x) \divider x \in \R \,, \,\, r>0  \}
$$
is a basis for $\TTe$ by Propostion \ref{proposition-metric-ball}. Note that balls in $\R$ are just open intervals
$$
B_r(x) = (x-r,x+r) \,.
$$
Hence $\mathcal{B}_1 = \mathcal{B}$, so that $\mathcal{B}_1$ is a basis for $\TTe$.

2. $\mathcal{B}_2$ is a basis for $\TTe$. This is because any open interval $(a,b)$ with $a,b \in \R$ can be written as
$$
\bigcup_{q,r \in \Q , \, a< q , \, s<b} (q,s) = (a,b) \,.
$$
Therefore, since $\mathcal{B}_1$ is a basis for $\TTe$, we conclude that also $\mathcal{B}_2$ is a basis for $\TTe$.


3. $\mathcal{B}_3$ is not a basis for $\TTe$. Indeed, consider $U = (0,1/2)$, which is open in $\TTe$. It is clear that $U$ cannot be obtained as the union of intervals $(q,s)$ with $q,s \in \Z$.



:::





::: {.Proposition  #proposition-basis}


Let $(X,\TT)$ be a topological space, and $\mathcal{B}$ a basis for $\TT$. They hold:

- (B1) We have
$$
\bigcup_{B \in \mathcal{B}} \, B = X \,.
$$

- (B2) If $U_1,U_2 \in \mathcal{B}$ then there exist $\{B_i \} \subseteq \mathcal{B}$ such that
$$
U_1 \cap U_2 = \bigcup_{i \in I} \, B_i \,.
$$

:::





::: {.Proposition  #proposition-topology-basis}


Let $X$ be a set, and $\mathcal{B}$ a collection of subsets of $X$ satisfying (B1)-(B2). Define
$$
\TT := \left\{  U \subseteq X \divider U = \bigcup_{i \in I} B_i \,, \,\, B_i \in \mathcal{B}     \right\} \,.
$$
Then $\TT$ is a topology on $X$, with basis given by $\mathcal{B}$.


:::






## Product topology

::: Proposition
 
Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be topological spaces. Define the family $\mathcal{B}$ of subsets
of $X \times Y$ as
$$
\mathcal{B} := \{   U \times V \divider U \in \TT_X \,, \,\, V \in \TT_Y  \} \subseteq \TT_X \times \TT_Y \,.
$$
Then $\mathcal{B}$ satisfies properties (B1) and (B2) from Proposition \ref{proposition-basis}. In particular,
$$
\TT_{X \times Y} := \left\{  Z  \, \divider \, Z =  \bigcup_{i \in I} U_i \times V_i , \,\, U_i \times V_i \in \mathcal{B}   \right\} 
$${#eq-product-topology}
is a topology on $X \times Y$. 

:::




::: Definition
### Product topology

Let $(X,\TT_X)$ and $(Y,\TT_Y)$ be topological spaces. The **product topology** on $X \times Y$ is the collection of sets
$\TT_{X \times Y}$ at (@eq-product-topology).

:::


::: Example 

Let $\R$ be equipped with the (one dimensional) Euclidean topology. The product topology on $\R \times \R$ coincides with the topology 
on $\R^2$ equipped with the (two dimensional) Euclidean topology. 

:::




## Connectedness

::: Definition
### Connected space

Let $(X,\TT)$ be a topological space. We say that:

1. $X$ is **connected** if the only subsets of $X$ which are both open and closed are $\emptyset$ and $X$. 
2. $X$ is **disconnected** if it is not connected.

:::


::: Definition
### Proper subset

Let $X$ be a set. A subset $A \subseteq X$ is **proper** if 
$A \neq \emptyset$ and $A \neq X$.

:::


::: Proposition
### Equivalent definition for connectedness {#proposition-connected-equivalent}

Let $(X,\TT)$ be a topological space. They are equivalent:

1. $X$ is disconnected.
2. $X$ is the disjoint union of two proper open subsets.
3. $X$ is the disjoint union of two proper closed subsets. 

:::



::: Example

**Question.** Consider the set $X = \{0,1\}$ with the subspace topology induced by the inclusion $X \subseteq \R$, where $\R$ is equipped with the
Euclidean topology $\TTe$. Prove that $X$ is disconnected.

**Solution.** Note that 
$$
X = \{ 0 \} \cup \{ 1 \} \,, \quad \{ 0 \} \cap \{ 1 \} = \emptyset \,.
$$
The set $\{ 0 \}$ is open for the subspace topology, since
$$
\{ 0 \} = X \cap (-1,1) \,, \quad 
(-1,1) \in \TTe \,.
$$
Similarly, also $\{ 1 \}$ is open for the subspace topology, since
$$
\{ 1 \} = X \cap (0,2) \,, \quad 
(0,2) \in \TTe \,.
$$
Since $\{ 0 \}$ and $\{ 1 \}$ are proper subsets of $X$, 
we conclude that $X$ is disconnected.

:::


::: {.Example  #example-R-minus-p}

**Question.** Let $\R$ be equipped with $\TTe$, and let $p \in \R$. Prove that the set $X = \R \smallsetminus \{p\}$ is disconnected. 

**Solution.** Define the sets 
$$ 
A = (-\infty,p) \,, \quad B = (p , \infty) \,.
$$
$A$ and $B$ are proper subsets of $X$. Moreover 
$$
X = A \cup B \,,  \quad A \cap B = \emptyset \,.
$$
Finally, $A,B$ are open for the subspace topology on $X$, since
they are open in $(\R,\TTe)$. Therefore $X$ is disconnected.

:::


::: {.Theorem #theorem-connected}

Let $(X,\TT_X)$, $(Y,\TT_Y)$ be topological spaces. Suppose that
$f \colon X \to Y$ is continuous and let $f(X) \subseteq Y$ be 
equipped with the subspace topology. If $X$ is connected, then $f(X)$ is connected. 

:::



::: Theorem  
### Connectedness is topological invariant {#theorem-invariant-connected}

Let $(X,\TT_X)$, $(Y,\TT_Y)$ be homeomorhic topological spaces. 
Then
$$
X \, \mbox{ is connected } \,\, \iff \,\,
Y \, \mbox{ is connected } 
$$

:::


::: Example

**Question.** Define the one dimensional unit circle
$$
\sphere^1 := \{(x,y) \in \mathbb{R}^2 \, \colon \, x^2 + y^2 = 1 \} \,.
$$
Prove that $\sphere^1$ and $[0,1]$ are not homeomorphic. 


**Solution.** Suppose by contradiction that there exists a homeomorphism
$$
f  \colon [0,1] \to \mathbb{S}^1 \,.
$$
The restriction of $f$ to $[0,1] \smallsetminus \{\frac12\}$ defines a homeomorphism 
$$
g \ \colon \left( [0,1] \smallsetminus \left\{\frac12\right\} \right) \to \left( \sphere^1 \smallsetminus \{\mathbf{p}\} \right) \,, \quad \mathbf{p} := f\left(\frac12 \right) \,.
$$
The set $[0,1] \smallsetminus \left\{ \frac12 \right\}$ is disconnected, 
since 
$$
[0,1] \smallsetminus \{1/2\} = [0,1/2) \, \cup \, (1/2,1] 
$$
with $[0,1/2)$ and $(1/2,1]$ open for the subset topology, non-empty and disjoint. Therefore, using that $g$ is a homeomorphism, we conclude that also $\sphere^1 \smallsetminus \{\mathbf{p}\}$ is disconnected. Let $\theta_0 \in [0,2\pi)$ be the unique angle such that 
$$
\mathbf{p} = (\cos (\theta_0),\sin(\theta_0)) \,.
$$
Thus $\sphere^1 \smallsetminus \{\mathbf{p}\}$ is parametrized by
$$
\g(t):=(\cos(t),\sin(t)) \,, \quad t \in (\theta_0,\theta_0 + 2\pi) \,.
$$ 
Since $\g$ is continuous and $(\theta_0,\theta_0 + 2\pi)$ is connected, by Theorem \ref{theorem-connected}, we conclude that $\sphere^1 \smallsetminus \{\mathbf{p}\}$ is connected. Contradiction.

:::





::: Definition
### Interval

A subset $I \subset \R$ is an interval if it holds:
$$
\forall \, a,b \in I \,, \, x \in \R  \, \st a<x<b \quad 
\implies \quad x \in I \,.
$$

:::

::: Theorem  
### Intervals are connected {#theorem-interval-connected}

Let $\R$ be equipped with the Euclidean topology and let $I \subseteq \R$. They are equivalent:

1. $I$ is connected.
2. $I$ is an interval.

:::



::: Theorem
### Intermediate Value Theorem

Let $(X,\TT)$ be a connected topological space. Suppose that 
$f \colon X \to \R$ is continuous. Suppose that $a,b \in X$ are such that $f(a)<f(b)$. It holds:
$$
\forall \, c \in \R \st f(a)< c < f(b) \,, \,\, \exists \, \xi \in X \st f(\xi) = c \,.
$$

:::


::: Example
### Intervals are connected - Alternative proof

**Question.** Prove the following statements.

1. Let $(X,\TT)$ be a disconnected topological space. Prove that there exists a function $f \colon X \to \{0,1\}$ which is continuous and surjective.

2. Consider $\R$ equipped with the Euclidean topology. Let $I \subseteq \R$ be an interval. Use point (1), and the Intermediate Value Theorem in $\R$ (see statement below), to show that $I$ is connected.  

*Intermediate Value Theorem in $\R$*: Suppose that $f \colon [a,b] \to \R$ is continuous, and $f(a) < f(b)$. Let $c \in \R$ be such that $f(a) \leq c \leq f(b)$. Then, there exists $\xi \in [a,b]$ such that $f(\xi) = c$.

**Solution. Part 1.** Since $X$ is disconnected, there exist $A,B \in \TT$ proper and such that
$$
X = A \cup B \,, \quad A \cap B = \emptyset \,.
$$
Define $f \colon X \to \{0,1\}$ by
$$
f(x) = 
\begin{cases}
	0 & \,\, \mbox{ if } \, x \in A \\
	1 & \,\, \mbox{ if } \, x \in B \\
\end{cases}
$$
Since $A$ and $B$ are non-empty, it follows that $f$ is surjective. Moreover $f$ is continuous: Indeed suppose $U \subseteq \R$ is open. We have 4 cases: 

- $0,1 \notin U$. Then $f^{-1}(U) = \emptyset \in \TT$.
- $0 \in U, \, 1 \notin U$. Then $f^{-1}(U) = A \in \TT$.
- $0 \notin U, \, 1 \in U$. Then $f^{-1}(U) = B \in \TT$.
- $0,1 \in U$. Then $f^{-1}(U) = X \in \TT$.

Then $f^{-1}(U) \in \TT$ for all $U \subseteq \R$ open, showing that $f$ is continuous.

**Part 2.** Let $I \subseteq \R$ be an interval. Suppose by contradiction $I$ is disconnected. By Point (1), there exists a map $f \colon I \to \{0,1\}$ which
is continuous and surjective. As $f$ is surjective, there exist $a,b \in I$ such that 
$$
f(a) = 0 \,, \quad  f(b) = 1 \,.
$$
Since $f$ is continuous, and $f(a) = 0 < 1 = f(b)$, by the *Intermediate Value Theorem in $\R$*, there exists $\xi \in [a,b]$ such that $f(\xi)=1/2$. As $I$ is an interval, $a,b \in I$, and $a\leq \xi \leq b$, it follows that $\xi \in I$. This is a contradiction, since $f$ maps $I$ into $\{0,1\}$, and $f(\xi) = 1/2 \notin \{0,1\}$. Therefore $I$ is connected.

:::



## Path-connectedness

::: Definition
### Path-connectedness

Let $(X,\TT)$ be a topological space. We say that $X$ is **path-connected** if for every $x,y \in X$ there exist $a,b \in \R$ with $a<b$, and a
continuous function 
$$
\alpha \colon [a,b] \to X  \,\, \st \,\, \alpha (a) = x \,, \quad \alpha(b) = y \,.
$$

:::





::: Theorem
### Path-connectedness implies connectedness {#theorem-path-connected}

Let $(X,\TT)$ be a path-connected topological space. Then $X$ is connected.

:::


::: Example

**Question.** Let $A \subseteq \R^n$ be convex. Show that $A$ is path-connected, and hence connected.


**Solution.** A is convex if for all $x,y \in A$ the segment connecting $x$ to $y$ is contained in $A$, namely,
$$
[x,y] := \{ (1-t)x + t y \divider t \in [0,1] \} \subseteq A \,.
$$
Therefore we can define
$$
\alpha \colon [0,1] \to A \,, \quad \alpha(t):=(1-t)x + t y \,.
$$
Clearly $\alpha$ is continuous, and $\alpha(0)=x, \alpha(1)=y$.
:::



::: Example
### Spaces of matrices

Let $\R^{2 \times 2}$ denote the space of real $2 \times 2$ matrices. Assume $\R^{2 \times 2}$ has the euclidean topology obtained by identifying it with $\R^4$.

1. Consider the set of orthogonal matrices 
$$
\mathrm{O}(2) = \{ A \in \R^{2 \times 2} \, \colon \, A^TA = I \} \,.
$$
Prove that $\mathrm{O}(2)$ is disconnected.

2. Consider the set of rotations
$$
\mathrm{SO}(2) = \{ A \in \R^{2 \times 2} \, \colon \, A^TA = I ,\,\, \det(A) = 1  \} \,.
$$
Prove that $\mathrm{SO}(2)$ is path-connected, and hence connected.



**Solution.** Let $A \in \mathrm{O}(2)$, and denote its entries by $a,b,c,d$. By direct calculation, the condition $A^T A = I$ is equivalent to
$$
a^2 + b^2 = 1 \,, \qquad b^2 + c^2 = 1 \,, \qquad ac + bd = 0 \,.
$$
From the first condition, we get that $a = \cos(t)$ and $b = \sin(t)$, for a suitable $t \in [0,2\pi)$. From the second and third conditions, we get $c = \pm \sin(t)$ and $d = \mp \cos(t)$. We decompose $\mathrm{O}(2)$ as
\begin{align*}
& \mathrm{O}(2) = A \cup B \,, \\
& A = \mathrm{SO}(2) = 
\left\{ 
\left(
\begin{array}{cc}
\cos(t) & -\sin(t) \\
\sin(t) & \cos(t)
\end{array} 
\right) , \, t \in [0,2\pi)  \right \} \\
& B = 
\left\{  
\left(
\begin{array}{cc}
\cos(t) & \sin(t) \\
\sin(t) & -\cos(t)
\end{array}
\right) , \, t \in [0,2\pi)  \right \} \,.
\end{align*}


1. The determinant function $\det \colon \mathrm{O}(2) \to \R$ is continuous. If $M \in A$, we have $\det(M) = 1$. If instead $M \in B$, we have $\det(M) = -1$. Moreover,
$$
{\det}^{-1}(\{1\}) = A \,, \qquad {\det}^{-1}(\{0\}) = B \,.
$$
As $\det$ is continuous, and $\{0\},\{1\}$ closed, we conclude that $A$ and $B$ are closed. Therefore, $A$ and $B$ are closed, proper and disjoint. Since $\mathrm{O}(2) = A \cup B$, we conclude that $\mathrm{O}(2)$ is disconnected.


2. Define the function $\psi \colon [0,2\pi) \to \mathrm{SO}(2)$ by
$$
\psi(t) = 
\left(
\begin{array}{cc}
\cos(t) & -\sin(t) \\
\sin(t) & \cos(t)
\end{array} 
\right) \,.
$$
Clearly, $\psi$ is continuous. Let $R,Q \in \mathrm{SO}(2)$. Then $R$ is determined by an angle $t_1$, while $Q$ by an angle $t_2$. Up to swapping $R$ and $Q$, we can assume $t_1 < t_2$. Define the function $f \colon [0,1] \to \mathrm{SO}(2)$ by
$$
f(\lambda) = \psi( t_1 (1-\lambda) + t_2 \lambda  ) \,. 
$$
Then, $f$ is continuous and 
$$
f(0) = \psi(t_1) = R, \quad f(1) = \psi(t_2) = Q \, .
$$
Thus $\mathrm{SO}(2)$ is path-connected.


:::

::: Warning

In general connectedness does not imply path-connectedness, as seen in Proposition \ref{proposition-topologist-curve}.

:::



::: Proposition 
### Topologist curve  {#proposition-topologist-curve}

Consider $\R^2$ with the Euclidean topology, and define the sets 
\begin{align*}
A & := \left\{   \left(  t, \sin \left( \frac{1}{t} \right)  \right) \divider t>0   \right\} \\
B & := \{(0,t) \divider t \in [-1,1] \}  \,, \qquad X := A \cup B  \,.
\end{align*}
Then $X$ is connected, but not path-connected.


:::



::: Theorem

Let $A \subseteq \R^n$ be **open** for the Euclidean topology. Then $A$ is connected if and only if it is path-connected.

:::




